### ISSUE TITLE
EVCC stopped working with Venus OS 3.50

### ISSUE THREAD

**Issue by asdt1803** [victronenergy/evcc-venusos-installer#3]
Hi,

I just upgraded my Cerbo to version 3.50 and it seems that EVCC cannot connect to my wallboy anymore. Maybe some new security feature prevents evcc from connecting? Is there a solution to this problem?

@400000006724bd4d0f900c04 *** starting evcc ***
@400000006724bd503469ea54 [main  ] INFO 2024/11/01 11:36:38 evcc 0.131.0
@400000006724bd5035da00cc [main  ] INFO 2024/11/01 11:36:38 using config file: /data/evcc/evcc.ve.yaml
@400000006724bd5036dff364 [db    ] INFO 2024/11/01 11:36:38 using sqlite database: /data/evcc/evcc.db
@400000006724bd561901d13c [mqtt  ] INFO 2024/11/01 11:36:44 connecting evcc-1546011885 at tcp://127.0.0.1:1883
@400000006724bd561a494944 [main  ] INFO 2024/11/01 11:36:44 listening at :7070
@400000006724bd561e788f5c [wattpilot] INFO 2024/11/01 11:36:44 Wattpilot connecting...
@400000006724bdf0001d982c {"level":"error","msg":"Auhtentication errormap[message:Wrong password type:authError]","time":"2024-11-01T11:39:17Z","wattpilot":"192.168.11.132"}
@400000006724bdf003bd736c [main  ] FATAL 2024/11/01 11:39:18 cannot create charger 'wallbox1': cannot create charger type 'template': cannot create charger type 'wattpilot': could not connect
@400000006724bdf003bda24c [main  ] FATAL 2024/11/01 11:39:18 will attempt restart in: 15m0s

**Comment by premultiply** [comment]
> message:Wrong password

Scheint mir sehr eindeutig zu sein.

**Comment by asdt1803** [comment]
Nicht wirklich. Die evcc.ve.yaml wurde nicht verändert und funktioniert problemlos auf einem anderen Linux-Rechner. Character encoding vielleicht?

**Comment by premultiply** [comment]
Aber die Wallbox geupdatet etc.?

Ohnehin solltest du die Anbindung auf OCPP umstellen. Die bisherige Websocket-API-Anbindung gilt als veraltet.

**Comment by asdt1803** [comment]
Die einzige Aktion war, am Cerbo das Update durchzuführen. Ansonsten habe ich gar nichts verändert. 
Also so: Update klicken, reboot abwarten, evcc startet nicht mehr.

Den Tipp mit OCPP werde ich beherzigen. Ansonsten läuft evcc ja erstmal auf dem anderen Rechner.

**Comment by asdt1803** [comment]
Mit OCPP funktioniert es. Vielen Dank für den Tipp.

**Comment by asdt1803** [comment]
Mit OCPP funktioniert es. Vielen Dank für den Tipp.
